version: '2'
services:
  mosquitto:
    build:
      context: .
      dockerfile: mosquitto/Dockerfile
    ports:
      - "1883:1883"

  home_assistant:
    image: homeassistant/home-assistant
    ports:
      - "8123:8123"
    depends_on:
      - mosquitto
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./home_assistant/config:/config"

networks:
  bridge:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24
        gateway: 192.168.1.1 
