version: '2'
services:
  mosquitto:
    build:
      context: .
      dockerfile: mosquitto/Dockerfile
    ports:
      - "1883:1883"

  mosquitto-subscriber:
    build:
      context: .
      dockerfile: mosquitto-client/Dockerfile.sub
    depends_on: 
      - mosquitto

  mosquitto-publisher:
    build:
      context: .
      dockerfile: mosquitto-client/Dockerfile.pub
    depends_on:
      - mosquitto
      - mosquitto-subscriber
