version: '2'
services:
  mosquitto:
    build:
      context: .
      dockerfile: mosquitto/Dockerfile
    ports:
      - "1883:1883"
 
  mosquitto-subscriber:
    env_file: .env
    command: [-t, test]
    build:
      context: mosquitto-client
      dockerfile: Dockerfile.sub
    volumes:
      - ./ca:/ca
    links:
      - mosquitto:mqtt.local
    depends_on: 
      - mosquitto
