FROM armhf/ubuntu:16.04

RUN apt-get update -y \
	&& apt-get install -y python-software-properties
RUN apt-get update -y \
	&& apt-get install -y mosquitto-clients

ENTRYPOINT [ "mosquitto_sub", "-h", "mqtt.local", "-p", "8883", "--cafile", "/ca/ca.crt.pem", "--cert", "/ca/mqtt-client.local.crt.pem", "--key", "/ca/mqtt-client.local.key.pem" ]
CMD [ "-t", "test" ]
