FROM armhf/ubuntu:16:04

RUN apt-get update -y \
	&& apt-get install -y python-software-properties
	&& apt-get install -y mosquitto-clients

ENTRYPOINT [ "mosquitto_pub", "-h", "mqtt.local" ]
CMD [ "-t", "test", "-m", "Hello World" ]
